### ISSUE TITLE
Daz poses

### ISSUE THREAD

**Issue by drBenway** [nkeeline/Keemap-Blender-Rig-ReTargeting-Addon#2]
Hi Nick,

I was wondering if 
- your script could be used to map exported Daz poses via fbx to a rigify armature. 
- the json file that I generate would be generic and thus be reusable for other. If this is the case would you then accept other peoples json files in your repo? (have a contrib guide)

kind regards

**Comment by nkeeline** [comment]
Yes, I have already mapped Daz characters with the script.  The gremlin character in the video is from Daz.  That being said, Daz exports have lots of constraints that fight the script so make sure you turn them off.  Yes a single JSON file will work for most daz exports, I placed a Radical2Daz.json in the examples folder.  I would need to make a file for every possible destination and it's corresponding possible source, if this were easy I wouldn't have made a UI that let's you customize it:)
