### ISSUE TITLE
Add-on Issue

### ISSUE THREAD

**Issue by djreal15** [nkeeline/Keemap-Blender-Rig-ReTargeting-Addon#3]
Hey Nick,

I seem to have an issue where it is not available on my add-on toolbar. Do you have any fixes you recommend?

Thanks

**Comment by ark-tik** [comment]
I'm also facing same issue with Blender 2.90.1

**Comment by ark-tik** [comment]
Alright, it was my fault, it only shows up in pose mode.

**Comment by nkeeline** [comment]
when the addon doesn't show up it's usually one of two reasons:
1. The zip file you are installing is a zip of a zip, open the zip file and make sure there isn't another zip inside the one you are trying to install.
2. After installing you are not in pose mode so you don't see the add on tag.

**Comment by nkeeline** [comment]
closing
