### ISSUE TITLE
Transferring from quaternion rigs causes gimbal lock

### ISSUE THREAD

**Issue by yokimklein** [nkeeline/Keemap-Blender-Rig-ReTargeting-Addon#5]
As the addon converts rotations to XYZ Euler when transferring from one rig to another, if the source rig uses quaternion rotations the destination rig can suffer from gimbal lock, leading to bad results.

This addon has been fantastic so far. It would be great if it would support quaternion animations in the future *wink wink nudge nudge* :)

**Comment by burgalon** [comment]
+1

**Comment by nkeeline** [comment]
v0.0.9 released with quaternion mode.  please select quaternion mode in the main settings and you should be good to go:)
