### ISSUE TITLE
Transfer animation does not include location?

### ISSUE THREAD

**Issue by seemon2** [nkeeline/Keemap-Blender-Rig-ReTargeting-Addon#6]
Hi,

I am having problem transferring the animation with the "location" .. 
My source rig (BVH) has motion that moves from position to position ..   but after I done the mapping of bones, and do the "transfer animation" .. only the rotation motion is transferred, but not the position motion.
Is there something I need to set up to get this position motion/animation transferred ?

I tried to tick off the "hip" (root) bone for "set position to bone" thinking this maybe the cause but still the same results.
The targeted rig (Mixamo) stay stationary in 1 position but do have rotation motion working fine.

Please help / advise is this a limitation of this tool? I am running on Blender 2.92.

**Comment by nkeeline** [comment]
The mapping of the root bone of the source to target rig needs to have Set Position of Bone checked, that's all, it should work unless the target bone's position is locked or isn't allowed to move.  Make sure in pose mode you can move the position of the target bone with the G key in blender.

**Comment by nkeeline** [comment]
should be resolve with v0.0.5
