### ISSUE TITLE
Other colors

### ISSUE THREAD

**Issue by hansnolte** [nkeeline/Keemap-Blender-Rig-ReTargeting-Addon#9]
Hi, Nick,
wonderful Addon.

Is it possible to display the mapped bones in a different color.
It would greatly increase the clarity of complex amatures.

Do you have plans for a "semi-automatic" with the mapping of the bones ala Rococo?

Many greetings 
Hans

**Comment by nkeeline** [comment]
We purchased a rokoko suit and modified the script to work with it.  We are using rokoku in production with these changes right now.  I'm sorry about color changes, I am not going to implement that due to higher priorities.
